/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modelo;

/**
 *
 * @author Chris
 */
public class CheckInOut extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CheckInOut.class.getName());
    private clases.SistemaHotel sistema;

    /**
     * Creates new form CheckInOut
     */
    public CheckInOut() {
        this(new clases.SistemaHotel());
    }

    public CheckInOut(clases.SistemaHotel sistema) {
        this.sistema = sistema;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoEstadia = new javax.swing.JTextField();
        btnBuscarEstadia = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblFechaInicioEstadia = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblFechaFinEstadia = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnCheckIn = new javax.swing.JButton();
        btnCheckOut = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnVolverEstadia = new javax.swing.JButton();
        lblHabitacionEstadia = new javax.swing.JLabel();
        lblEstadoEstadia = new javax.swing.JLabel();
        lblTipoHabitacionEstadia = new javax.swing.JLabel();
        lblHuespedEstadia = new javax.swing.JLabel();
        lblNochesEstadia = new javax.swing.JLabel();
        lblTotalServiciosEstadia = new javax.swing.JLabel();
        lblTotalHabitacionEstadia = new javax.swing.JLabel();
        lblTotalPagarEstadia = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CHECK IN / CHECK OUT");

        jLabel2.setText("CODIGO DE RESERVA / ESTADIA:");

        btnBuscarEstadia.setText("BUSCAR");
        btnBuscarEstadia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEstadiaActionPerformed(evt);
            }
        });

        jLabel3.setText("DATOS DE LA RESERVA:");

        jLabel4.setText("HUESPED:");

        jLabel5.setText("TIPO DE HABITACION:");

        jLabel6.setText("FECHA DE INICIO:");

        jLabel8.setText("FECHA DE FIN:");

        jLabel10.setText("HABITACION ASIGNADA:");

        jLabel11.setText("ESTADO ACTUAL:");

        btnCheckIn.setText("REALIZAR CHECK IN");
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });

        btnCheckOut.setText("REALIZAR CHECK OUT");
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });

        jLabel12.setText("INFORMACION DE FACTURA (SOLO PARA CHECKOUT) :");

        jLabel13.setText("NOCHES:");

        jLabel14.setText("TOTAL HABITACIÓN:");

        jLabel15.setText("TOTAL SERVICIOS:");

        jLabel16.setText("TOTAL A PAGAR:");

        btnVolverEstadia.setText("VOLVER AL MENU PRINCIPAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblEstadoEstadia))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblHabitacionEstadia))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel5))
                                            .addGap(4, 4, 4)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblTipoHabitacionEstadia)
                                                .addComponent(lblFechaInicioEstadia)
                                                .addComponent(lblHuespedEstadia)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCodigoEstadia, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(btnBuscarEstadia))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCheckOut)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblFechaFinEstadia))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnCheckIn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNochesEstadia)
                            .addComponent(btnVolverEstadia)
                            .addComponent(lblTotalServiciosEstadia)
                            .addComponent(lblTotalHabitacionEstadia)
                            .addComponent(lblTotalPagarEstadia))))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(245, 245, 245))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigoEstadia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarEstadia))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblHuespedEstadia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblTipoHabitacionEstadia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblFechaInicioEstadia)
                    .addComponent(jLabel8)
                    .addComponent(lblFechaFinEstadia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblHabitacionEstadia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblEstadoEstadia))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckIn)
                    .addComponent(btnCheckOut))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblNochesEstadia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblTotalHabitacionEstadia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblTotalServiciosEstadia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblTotalPagarEstadia))
                .addGap(18, 18, 18)
                .addComponent(btnVolverEstadia)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
    String codigo = txtCodigoEstadia.getText().trim();

    if (codigo.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Ingrese el código de reserva/estadia.",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Aquí se registraría el CHECK-IN de la reserva/estadia: " + codigo,
            "Check-in",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_btnCheckInActionPerformed

    private void btnBuscarEstadiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEstadiaActionPerformed
    String criterio = txtCodigoEstadia.getText().trim();

    if (criterio.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Ingrese el código de reserva/estadia.",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    // TODO: buscar en SistemaHotel la reserva/estadia y llenar los labels:
    // lblHuespedEstadia, lblTipoHabitacionEstadia, lblFechaInicioEstadia, etc.

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Aquí se mostrarían los datos de la reserva/estadia con código: " + criterio,
            "Buscar estadía",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_btnBuscarEstadiaActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
    String codigo = txtCodigoEstadia.getText().trim();

    if (codigo.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Busque primero una estadía para hacer el check-out.",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    // TODO:
    // 1. Calcular noches, total habitación y total servicios.
    // 2. Llenar labels: lblNochesEstadia, lblTotalHabitacionEstadia,
    //    lblTotalServiciosEstadia, lblTotalPagarEstadia.
    // 3. Cambiar estado de habitación a SUCIA/EN LIMPIEZA.

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Aquí se registraría el CHECK-OUT de la estadía: " + codigo +
            "\n(se calcularía el monto total).",
            "Check-out",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_btnCheckOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CheckInOut().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEstadia;
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnVolverEstadia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblEstadoEstadia;
    private javax.swing.JLabel lblFechaFinEstadia;
    private javax.swing.JLabel lblFechaInicioEstadia;
    private javax.swing.JLabel lblHabitacionEstadia;
    private javax.swing.JLabel lblHuespedEstadia;
    private javax.swing.JLabel lblNochesEstadia;
    private javax.swing.JLabel lblTipoHabitacionEstadia;
    private javax.swing.JLabel lblTotalHabitacionEstadia;
    private javax.swing.JLabel lblTotalPagarEstadia;
    private javax.swing.JLabel lblTotalServiciosEstadia;
    private javax.swing.JTextField txtCodigoEstadia;
    // End of variables declaration//GEN-END:variables
}
