/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modelo;
/**
 *
 * @author Chris
 */
public class CrearModificarResrva extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrearModificarResrva.class.getName());
    private final clases.SistemaHotel sistema;
    private final clases.Reservacion reservacion;

    /**
     * Creates new form CrearModificarResrva
     */
    public CrearModificarResrva(clases.SistemaHotel sistema, clases.Reservacion reservacion) {
        if (sistema == null) {
            throw new IllegalArgumentException("El sistema no puede ser nulo");
        }
        this.sistema = sistema;
        this.reservacion = reservacion;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbHuespedReserva = new javax.swing.JComboBox<>();
        cmbTipoHabitacionReserva = new javax.swing.JComboBox<>();
        txtFechaInicioReserva = new javax.swing.JFormattedTextField();
        txtFechaFinReserva = new javax.swing.JFormattedTextField();
        btnVerificarReserva = new javax.swing.JButton();
        lblMensajeReserva = new javax.swing.JLabel();
        btnGuardarReserva = new javax.swing.JButton();
        btnCancelarReservaForm = new javax.swing.JButton();
        btnLimpiarReserva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel1.setText("NUEVA RESERVA");

        jLabel2.setText("Huesped:");

        jLabel3.setText("TIPO DE HABITACION:");

        jLabel4.setText("FECHA DE INICIO:");

        jLabel5.setText("FECHA DE FIN:");

        cmbTipoHabitacionReserva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIMPLE", "DOBLE", "SUITE" }));

        try {
            txtFechaInicioReserva.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtFechaFinReserva.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnVerificarReserva.setText("VERIFICAR DISPONIBILIDAD");
        btnVerificarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarReservaActionPerformed(evt);
            }
        });

        btnGuardarReserva.setText("GUARDAR");
        btnGuardarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarReservaActionPerformed(evt);
            }
        });

        btnCancelarReservaForm.setText("CANCELAR");

        btnLimpiarReserva.setText("LIMPIAR");
        btnLimpiarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarReservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(btnGuardarReserva))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtFechaInicioReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFechaFinReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbTipoHabitacionReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbHuespedReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMensajeReserva))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpiarReserva)
                        .addGap(63, 63, 63)
                        .addComponent(btnCancelarReservaForm)
                        .addGap(23, 23, 23)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(185, 185, 185))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVerificarReserva)
                        .addGap(146, 146, 146))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbHuespedReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbTipoHabitacionReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFechaInicioReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFechaFinReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerificarReserva)
                    .addComponent(lblMensajeReserva))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarReserva)
                    .addComponent(btnCancelarReservaForm)
                    .addComponent(btnLimpiarReserva))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarReservaActionPerformed
    String tipo = cmbTipoHabitacionReserva.getSelectedItem().toString();
    String fechaInicio = txtFechaInicioReserva.getText().trim();
    String fechaFin = txtFechaFinReserva.getText().trim();

    if (fechaInicio.isEmpty() || fechaFin.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Ingrese fecha de inicio y fin.",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    // Más adelante: consultar SistemaHotel para ver habitaciones libres
    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Aquí se verificaría la disponibilidad para tipo " + tipo +
            " entre " + fechaInicio + " y " + fechaFin,
            "Verificar disponibilidad",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_btnVerificarReservaActionPerformed

    private void btnGuardarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarReservaActionPerformed
    String huesped = (String) cmbHuespedReserva.getSelectedItem();
    String tipoHabitacion = (String) cmbTipoHabitacionReserva.getSelectedItem();
    String fechaInicio = txtFechaInicioReserva.getText().trim();
    String fechaFin = txtFechaFinReserva.getText().trim();

    if (huesped == null || tipoHabitacion == null ||
        fechaInicio.isEmpty() || fechaFin.isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Complete huésped, tipo de habitación y fechas.",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Reserva creada en memoria (falta conectarla con SistemaHotel).",
            "Info",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
    );

    this.dispose();
    }//GEN-LAST:event_btnGuardarReservaActionPerformed

    private void btnLimpiarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarReservaActionPerformed
    cmbHuespedReserva.setSelectedIndex(0);
    cmbTipoHabitacionReserva.setSelectedIndex(0);
    txtFechaInicioReserva.setText("");
    txtFechaFinReserva.setText("");
    lblMensajeReserva.setText("");
    }//GEN-LAST:event_btnLimpiarReservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            clases.SistemaHotel sistema = new clases.SistemaHotel(100, 100, 100, 100, 100, 100);
            new CrearModificarResrva(sistema, null).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarReservaForm;
    private javax.swing.JButton btnGuardarReserva;
    private javax.swing.JButton btnLimpiarReserva;
    private javax.swing.JButton btnVerificarReserva;
    private javax.swing.JComboBox<String> cmbHuespedReserva;
    private javax.swing.JComboBox<String> cmbTipoHabitacionReserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblMensajeReserva;
    private javax.swing.JFormattedTextField txtFechaFinReserva;
    private javax.swing.JFormattedTextField txtFechaInicioReserva;
    // End of variables declaration//GEN-END:variables
}
