/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modelo;

/**
 *
 * @author Chris
 */
public class GestionDeServiciosAdicionales extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestionDeServiciosAdicionales.class.getName());

    /**
     * Creates new form GestionDeServiciosAdicionales
     */
    public GestionDeServiciosAdicionales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnNuevoServicio = new javax.swing.JButton();
        btnEditarServicio = new javax.swing.JButton();
        btnDesactivarServicio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarServicio = new javax.swing.JTextField();
        btnBuscarServicio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServicios = new javax.swing.JTable();
        btnVolverServicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setText("GESTION DE SERVICIOS ADICIONALES");

        btnNuevoServicio.setText("NUEVO");
        btnNuevoServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoServicioActionPerformed(evt);
            }
        });

        btnEditarServicio.setText("EDITAR");
        btnEditarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarServicioActionPerformed(evt);
            }
        });

        btnDesactivarServicio.setText("DESACTIVAR");
        btnDesactivarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarServicioActionPerformed(evt);
            }
        });

        jLabel2.setText("BUSCAR:");

        btnBuscarServicio.setText("BUSCAR");
        btnBuscarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarServicioActionPerformed(evt);
            }
        });

        tblServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NOMBRE", "PRECIO", "ACTIVO"
            }
        ));
        jScrollPane1.setViewportView(tblServicios);

        btnVolverServicio.setText("VOLVER AL MENU PRINCIPAL");
        btnVolverServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverServicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnNuevoServicio)
                        .addGap(44, 44, 44)
                        .addComponent(btnEditarServicio)
                        .addGap(45, 45, 45)
                        .addComponent(btnDesactivarServicio)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarServicio))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVolverServicio)
                        .addGap(222, 222, 222))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(168, 168, 168))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoServicio)
                    .addComponent(btnEditarServicio)
                    .addComponent(btnDesactivarServicio)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarServicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVolverServicio)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDesactivarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarServicioActionPerformed
    int fila = tblServicios.getSelectedRow();

    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Seleccione un servicio para desactivarlo.",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    String codigo = (String) tblServicios.getValueAt(fila, 0);

    // Más adelante: buscar en SistemaHotel y marcarlo como inactivo
    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Aquí se marcaría como INACTIVO el servicio: " + codigo,
            "Desactivar servicio",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_btnDesactivarServicioActionPerformed

    private void btnNuevoServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoServicioActionPerformed
    RegistroDeServicio frm = new RegistroDeServicio();
    frm.setLocationRelativeTo(this);
    frm.setVisible(true);
    }//GEN-LAST:event_btnNuevoServicioActionPerformed

    private void btnEditarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarServicioActionPerformed
    int fila = tblServicios.getSelectedRow();

    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Seleccione un servicio de la tabla.",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    String codigo = (String) tblServicios.getValueAt(fila, 0);

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Aquí se editaría el servicio con código: " + codigo,
            "Editar servicio",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_btnEditarServicioActionPerformed

    private void btnBuscarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarServicioActionPerformed
    String texto = txtBuscarServicio.getText().trim();

    if (texto.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Ingrese un código o nombre para buscar.",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    // Más adelante: filtrar tabla con datos de SistemaHotel
    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Aquí se filtraría la tabla usando: " + texto,
            "Buscar servicio",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_btnBuscarServicioActionPerformed

    private void btnVolverServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverServicioActionPerformed
    this.dispose();
    }//GEN-LAST:event_btnVolverServicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GestionDeServiciosAdicionales().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarServicio;
    private javax.swing.JButton btnDesactivarServicio;
    private javax.swing.JButton btnEditarServicio;
    private javax.swing.JButton btnNuevoServicio;
    private javax.swing.JButton btnVolverServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblServicios;
    private javax.swing.JTextField txtBuscarServicio;
    // End of variables declaration//GEN-END:variables
}
