/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modelo;

/**
 *
 * @author Chris
 */
public class GestionDeReservas extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestionDeReservas.class.getName());
    private clases.SistemaHotel sistema;

    /**
     * Creates new form GestionDeReservas
     */
    public GestionDeReservas(clases.SistemaHotel sistema) {
        if (sistema == null) {
            throw new IllegalArgumentException("El sistema no puede ser nulo");
        }
        this.sistema = sistema;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        cargarReservas(sistema.getReservaciones());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNuevaReserva = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnModificarReserva = new javax.swing.JButton();
        btnCancelarReserva = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarReserva = new javax.swing.JTextField();
        btnBuscarReserva = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReservas = new javax.swing.JTable();
        btnVolverReserva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));

        btnNuevaReserva.setText("NUEVA RESERVA");
        btnNuevaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaReservaActionPerformed(evt);
            }
        });

        jLabel1.setText("GESTION DE RESERVAS");

        btnModificarReserva.setText("MODIFICAR");
        btnModificarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarReservaActionPerformed(evt);
            }
        });

        btnCancelarReserva.setText("CANCELAR");
        btnCancelarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarReservaActionPerformed(evt);
            }
        });

        jLabel2.setText("BUSCAR POR DNI HUESPED:");

        btnBuscarReserva.setText("BUSCAR");
        btnBuscarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarReservaActionPerformed(evt);
            }
        });

        tblReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "HUESPED", "TIPO HABITACION", "F. INICIO", "F. FIN", "ESTADO"
            }
        ));
        jScrollPane1.setViewportView(tblReservas);

        btnVolverReserva.setText("VOLVER AL MENU PRINCIPAL");
        btnVolverReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverReservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNuevaReserva)
                            .addComponent(jLabel2))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnModificarReserva)
                                .addGap(105, 105, 105)
                                .addComponent(btnCancelarReserva))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBuscarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 86, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(btnVolverReserva)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevaReserva)
                    .addComponent(btnModificarReserva)
                    .addComponent(btnCancelarReserva))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarReserva))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnVolverReserva)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaReservaActionPerformed
    CrearModificarResrva frm = new CrearModificarResrva(sistema, null);  // modo "nueva"
    frm.setLocationRelativeTo(this);
    frm.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            cargarReservas(sistema.getReservaciones());
        }
    });
    frm.setVisible(true);
    }//GEN-LAST:event_btnNuevaReservaActionPerformed

    private void btnModificarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarReservaActionPerformed
    int fila = tblReservas.getSelectedRow();
    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Seleccione una reserva de la tabla.",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    // Más adelante usaremos el código para buscar la reservación real
    String codigo = (String) tblReservas.getValueAt(fila, 0);
    clases.Reservacion seleccionada = buscarReservacion(codigo);
    if (seleccionada == null) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "No se encontró la reserva seleccionada.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    CrearModificarResrva frm = new CrearModificarResrva(sistema, seleccionada);
    frm.setLocationRelativeTo(this);
    frm.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            cargarReservas(sistema.getReservaciones());
        }
    });
    frm.setVisible(true);
    }//GEN-LAST:event_btnModificarReservaActionPerformed

    private void btnCancelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarReservaActionPerformed
    int fila = tblReservas.getSelectedRow();
    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Seleccione una reserva para cancelarla.",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    String codigo = (String) tblReservas.getValueAt(fila, 0);
    clases.Reservacion seleccionada = buscarReservacion(codigo);
    if (seleccionada == null) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "No se encontró la reserva seleccionada.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    seleccionada.setEstado("CANCELADA");
    cargarReservas(sistema.getReservaciones());

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "La reserva " + codigo + " fue cancelada.",
            "Cancelar reserva",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_btnCancelarReservaActionPerformed

    private void btnBuscarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarReservaActionPerformed
    String texto = txtBuscarReserva.getText().trim();
    if (texto.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Ingrese un código, DNI o nombre de huésped para buscar.",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    java.util.List<clases.Reservacion> filtradas = new java.util.ArrayList<>();
    for (clases.Reservacion r : sistema.getReservaciones()) {
        if (r == null) {
            continue;
        }
        String huesped = r.getHuesped() != null
                ? (r.getHuesped().getDni() + " " + r.getHuesped().getApellidos() + " " + r.getHuesped().getNombres())
                : "";
        String cadena = (r.getCodigo() + " " + huesped).toLowerCase();
        if (cadena.contains(texto.toLowerCase())) {
            filtradas.add(r);
        }
    }

    cargarReservas(filtradas.toArray(new clases.Reservacion[0]));
    }//GEN-LAST:event_btnBuscarReservaActionPerformed

    private void btnVolverReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverReservaActionPerformed
    this.dispose();
    }//GEN-LAST:event_btnVolverReservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            clases.SistemaHotel sistema = new clases.SistemaHotel(100, 100, 100, 100, 100, 100);
            new GestionDeReservas(sistema).setVisible(true);
        });
    }

    private void cargarReservas(clases.Reservacion[] reservaciones) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblReservas.getModel();
        model.setRowCount(0);
        if (reservaciones == null) {
            return;
        }

        for (clases.Reservacion r : reservaciones) {
            if (r == null) {
                continue;
            }
            String huesped = r.getHuesped() != null
                    ? r.getHuesped().getApellidos() + ", " + r.getHuesped().getNombres()
                    : "";
            model.addRow(new Object[]{
                    r.getCodigo(),
                    huesped,
                    r.getTipoHabitacion(),
                    r.getFechaInicio(),
                    r.getFechaFin(),
                    r.getEstado()
            });
        }
    }

    private clases.Reservacion buscarReservacion(String codigo) {
        if (codigo == null) {
            return null;
        }
        for (clases.Reservacion r : sistema.getReservaciones()) {
            if (r != null && codigo.equals(r.getCodigo())) {
                return r;
            }
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarReserva;
    private javax.swing.JButton btnCancelarReserva;
    private javax.swing.JButton btnModificarReserva;
    private javax.swing.JButton btnNuevaReserva;
    private javax.swing.JButton btnVolverReserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReservas;
    private javax.swing.JTextField txtBuscarReserva;
    // End of variables declaration//GEN-END:variables
}
