/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modelo;

/**
 *
 * @author Chris
 */
public class GestionDeHuespedes extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestionDeHuespedes.class.getName());
    private clases.SistemaHotel sistema;
    private javax.swing.table.DefaultTableModel modeloTabla;

    /**
     * Creates new form GestionDeHuespedes
     */
    public GestionDeHuespedes() {
        this(new clases.SistemaHotel());
    }

    public GestionDeHuespedes(clases.SistemaHotel sistema) {
        this.sistema = sistema;
        initComponents();
        setLocationRelativeTo(null);
        configurarTabla();
        cargarHuespedes("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnNuevoHuesped = new javax.swing.JButton();
        btnEditarHuesped = new javax.swing.JButton();
        btnDesactivarHuesped = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarHuesped = new javax.swing.JTextField();
        btnBuscarHuesped = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHuespedes = new javax.swing.JTable();
        btnVolverHuesped = new javax.swing.JButton();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("GESTION DE HUESPEDES");

        btnNuevoHuesped.setText("NUEVO");
        btnNuevoHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoHuespedActionPerformed(evt);
            }
        });

        btnEditarHuesped.setText("EDITAR");
        btnEditarHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarHuespedActionPerformed(evt);
            }
        });

        btnDesactivarHuesped.setText("DESACTIVAR");
        btnDesactivarHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarHuespedActionPerformed(evt);
            }
        });

        jLabel2.setText("BUSCAR:");

        btnBuscarHuesped.setText("BUSCAR");
        btnBuscarHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarHuespedActionPerformed(evt);
            }
        });

        tblHuespedes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "APELLIDOS", "NOMBRES", "TELEFONO", "EMAIL", "ESTADO"
            }
        ));
        jScrollPane1.setViewportView(tblHuespedes);

        btnVolverHuesped.setText("VOLVER AL MENU PRINCIPAL");
        btnVolverHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverHuespedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnNuevoHuesped)
                        .addGap(44, 44, 44)
                        .addComponent(btnEditarHuesped)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDesactivarHuesped)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtBuscarHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarHuesped))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(btnVolverHuesped)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoHuesped)
                    .addComponent(btnEditarHuesped)
                    .addComponent(btnDesactivarHuesped)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscarHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarHuesped))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVolverHuesped)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDesactivarHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarHuespedActionPerformed
    int fila = tblHuespedes.getSelectedRow();

    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Seleccione un huésped de la tabla.",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    String dni = (String) tblHuespedes.getValueAt(fila, 0);
    clases.Huesped huesped = sistema.buscarHuespedPorDni(dni);

    if (huesped != null) {
        huesped.setEstado("INACTIVO");
        cargarHuespedes(txtBuscarHuesped.getText());
    }
    }//GEN-LAST:event_btnDesactivarHuespedActionPerformed

    private void btnNuevoHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoHuespedActionPerformed
    RegistroDeHuespedes frm = new RegistroDeHuespedes(sistema, null, () -> cargarHuespedes(txtBuscarHuesped.getText()));
    frm.setLocationRelativeTo(this);
    frm.setVisible(true);
    }//GEN-LAST:event_btnNuevoHuespedActionPerformed

    private void btnEditarHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarHuespedActionPerformed
    int fila = tblHuespedes.getSelectedRow();
    
    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Seleccione un huésped de la tabla.",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    String dni = (String) tblHuespedes.getValueAt(fila, 0);


    clases.Huesped huesped = sistema.buscarHuespedPorDni(dni);
    if (huesped == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "No se encontró el huésped seleccionado.");
        return;
    }

    RegistroDeHuespedes frm = new RegistroDeHuespedes(sistema, huesped, () -> cargarHuespedes(txtBuscarHuesped.getText()));
    frm.setLocationRelativeTo(this);
    frm.setVisible(true);
    }//GEN-LAST:event_btnEditarHuespedActionPerformed

    private void btnVolverHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverHuespedActionPerformed
    this.dispose();
    }//GEN-LAST:event_btnVolverHuespedActionPerformed

    private void btnBuscarHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHuespedActionPerformed
 String texto = txtBuscarHuesped.getText().trim();
    cargarHuespedes(texto);
    }//GEN-LAST:event_btnBuscarHuespedActionPerformed

    private void configurarTabla() {
        modeloTabla = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{"DNI", "APELLIDOS", "NOMBRES", "TELEFONO", "EMAIL", "ESTADO"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblHuespedes.setModel(modeloTabla);
    }

    private void cargarHuespedes(String filtro) {
        modeloTabla.setRowCount(0);
        String texto = filtro == null ? "" : filtro.toLowerCase();

        for (clases.Huesped h : sistema.getHuespedes()) {
            if (h == null) {
                continue;
            }

            boolean coincide = texto.isBlank()
                    || h.getDni().toLowerCase().contains(texto)
                    || h.getNombres().toLowerCase().contains(texto)
                    || h.getApellidos().toLowerCase().contains(texto);

            if (coincide) {
                modeloTabla.addRow(new Object[]{
                        h.getDni(),
                        h.getApellidos(),
                        h.getNombres(),
                        h.getContacto(),
                        h.getEmail(),
                        h.getEstado()
                });
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GestionDeHuespedes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarHuesped;
    private javax.swing.JButton btnDesactivarHuesped;
    private javax.swing.JButton btnEditarHuesped;
    private javax.swing.JButton btnNuevoHuesped;
    private javax.swing.JButton btnVolverHuesped;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHuespedes;
    private javax.swing.JTextField txtBuscarHuesped;
    // End of variables declaration//GEN-END:variables
}
