package modelo;

import clases.SistemaHotel;
import clases.Habitacion;
import javax.swing.table.DefaultTableModel;

public class GestionDeHabitaciones extends javax.swing.JFrame {
    private SistemaHotel sistema;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestionDeHabitaciones.class.getName());

    /**
     * Creates new form GestionDeHabitaciones
     */
public GestionDeHabitaciones() {
    this(new SistemaHotel());
}
private void cargarTablaHabitaciones() {
    DefaultTableModel modelo = (DefaultTableModel) tblHabitaciones.getModel();
    modelo.setRowCount(0); 

    if (sistema == null) {
        return;
    }

    Habitacion[] habs = sistema.getHabitaciones();
    if (habs == null) {
        return;
    }

    for (Habitacion h : habs) {
        if (h != null) {
            Object[] fila = new Object[] {
                h.getNumero(),
                h.getTipo(), 
                h.getCapacidadMax(), 
                h.getPrecioNoche(), 
                h.getEstado(),        
                "ACTIVA"             
            };
            modelo.addRow(fila);
        }
    }
}
public GestionDeHabitaciones(SistemaHotel sistema) {
    this.sistema = sistema;
    initComponents();
    setLocationRelativeTo(null);
    cargarTablaHabitaciones();   
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnNuevaHabitacion = new javax.swing.JButton();
        btnEditarHabitacion = new javax.swing.JButton();
        btnDesactivarHabitacion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarHabitacion = new javax.swing.JTextField();
        btnBuscarHabitacion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHabitaciones = new javax.swing.JTable();
        btnVolverHabitacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("GESTION DE HABITACIONES");

        btnNuevaHabitacion.setText("NUEVO");
        btnNuevaHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaHabitacionActionPerformed(evt);
            }
        });

        btnEditarHabitacion.setText("EDITAR");
        btnEditarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarHabitacionActionPerformed(evt);
            }
        });

        btnDesactivarHabitacion.setText("DESACTIVAR");
        btnDesactivarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarHabitacionActionPerformed(evt);
            }
        });

        jLabel2.setText("BUSCAR:");

        btnBuscarHabitacion.setText("BUSCAR");
        btnBuscarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarHabitacionActionPerformed(evt);
            }
        });

        tblHabitaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "N°", "TIPO", "CAPACIDAD", "PRECIO POR NOCHE", "ESTADO", "ACTIVA"
            }
        ));
        jScrollPane1.setViewportView(tblHabitaciones);

        btnVolverHabitacion.setText("VOLVER AL MENU PRINCIPAL");
        btnVolverHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverHabitacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 27, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevaHabitacion)
                                .addGap(63, 63, 63)
                                .addComponent(btnEditarHabitacion)
                                .addGap(47, 47, 47)
                                .addComponent(btnDesactivarHabitacion)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBuscarHabitacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarHabitacion))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(223, 223, 223)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(260, 260, 260)
                                .addComponent(btnVolverHabitacion)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevaHabitacion)
                    .addComponent(btnEditarHabitacion)
                    .addComponent(btnDesactivarHabitacion)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscarHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarHabitacion))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVolverHabitacion)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaHabitacionActionPerformed
    RegistroDeHabitacion frm = new RegistroDeHabitacion();
    frm.setLocationRelativeTo(this);
    frm.setVisible(true);
    }//GEN-LAST:event_btnNuevaHabitacionActionPerformed

    private void btnEditarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarHabitacionActionPerformed
    int fila = tblHabitaciones.getSelectedRow();
    
    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Seleccione una habitación de la tabla.",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    // Primera columna: número de habitación
    String numero = (String) tblHabitaciones.getValueAt(fila, 0);

    // Por ahora solo enviamos el número a la ventana de edición
javax.swing.JOptionPane.showMessageDialog(
        this,
        "Aquí se abriría la ventana para editar la habitación N° " + numero,
        "Editar habitación",
        javax.swing.JOptionPane.INFORMATION_MESSAGE
);
    }//GEN-LAST:event_btnEditarHabitacionActionPerformed

    private void btnDesactivarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarHabitacionActionPerformed
    int fila = tblHabitaciones.getSelectedRow();
    
    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Seleccione una habitación para desactivarla.",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    String numero = (String) tblHabitaciones.getValueAt(fila, 0);

    // Más adelante: buscar la habitación en SistemaHotel y marcarla como inactiva
    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Aquí se marcaría como INACTIVA la habitación N° " + numero,
            "Desactivar habitación",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_btnDesactivarHabitacionActionPerformed

    private void btnBuscarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHabitacionActionPerformed
    String texto = txtBuscarHabitacion.getText().trim();

    if (texto.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Ingrese un número o tipo de habitación para buscar.",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    // Más adelante filtraremos la tabla usando SistemaHotel
    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Aquí se filtraría la tabla de habitaciones usando: " + texto,
            "Buscar habitación",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_btnBuscarHabitacionActionPerformed

    private void btnVolverHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverHabitacionActionPerformed
    this.dispose();
    }//GEN-LAST:event_btnVolverHabitacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GestionDeHabitaciones().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarHabitacion;
    private javax.swing.JButton btnDesactivarHabitacion;
    private javax.swing.JButton btnEditarHabitacion;
    private javax.swing.JButton btnNuevaHabitacion;
    private javax.swing.JButton btnVolverHabitacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHabitaciones;
    private javax.swing.JTextField txtBuscarHabitacion;
    // End of variables declaration//GEN-END:variables
}
