/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modelo;
import clases.Habitacion; 

public class RegistroDeHabitacion extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroDeHabitacion.class.getName());
    private clases.SistemaHotel sistema;    

    /**
     * Creates new form RegistroDeHabitacion
     */
public RegistroDeHabitacion() {
    this(new clases.SistemaHotel());
}

public RegistroDeHabitacion(clases.SistemaHotel sistema) {
    initComponents();
    setLocationRelativeTo(null);
    this.sistema = sistema;
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbEstadoHabitacion = new javax.swing.JComboBox<>();
        cmbTipoHabitacion = new javax.swing.JComboBox<>();
        txtCapacidadHabitacion = new javax.swing.JTextField();
        txtPrecioHabitacion = new javax.swing.JTextField();
        txtNumeroHabitacion = new javax.swing.JTextField();
        btnGuardarHabitacion = new javax.swing.JButton();
        btnCancelarHabitacion = new javax.swing.JButton();
        btnLimpiarHabitacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("REGISTRO DE HABITACION");

        jLabel2.setText("NUMERO:");

        jLabel3.setText("CAPACIDAD MAXIMA:");

        jLabel4.setText("PRECIO POR NOCHE:");

        jLabel5.setText("TIPO:");

        jLabel6.setText("ESTADO INICIAL:");

        cmbEstadoHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LIBRE", "OCUPADA" }));

        cmbTipoHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIMPLE", "DOBLE", "SUITE" }));

        txtCapacidadHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapacidadHabitacionActionPerformed(evt);
            }
        });

        btnGuardarHabitacion.setText("GUARDAR");
        btnGuardarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarHabitacionActionPerformed(evt);
            }
        });

        btnCancelarHabitacion.setText("CANCELAR");
        btnCancelarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarHabitacionActionPerformed(evt);
            }
        });

        btnLimpiarHabitacion.setText("LIMPIAR");
        btnLimpiarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarHabitacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(btnGuardarHabitacion))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbEstadoHabitacion, 0, 142, Short.MAX_VALUE)
                                    .addComponent(cmbTipoHabitacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCapacidadHabitacion)
                                    .addComponent(txtPrecioHabitacion)
                                    .addComponent(txtNumeroHabitacion)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiarHabitacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addComponent(btnCancelarHabitacion))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumeroHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCapacidadHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrecioHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbEstadoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarHabitacion)
                    .addComponent(btnCancelarHabitacion)
                    .addComponent(btnLimpiarHabitacion))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarHabitacionActionPerformed
    // Número de habitación
    int numero;
    try {
        numero = Integer.parseInt(txtNumeroHabitacion.getText().trim());
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Ingrese un número de habitación válido (solo enteros).",
                "Número inválido",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    // Tipo
    String tipo = cmbTipoHabitacion.getSelectedItem().toString();

    // Capacidad máxima
    int capacidad;
    try {
        capacidad = Integer.parseInt(txtCapacidadHabitacion.getText().trim());
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Ingrese una capacidad válida (solo números enteros).",
                "Capacidad inválida",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    // Precio por noche
    String precioTexto = txtPrecioHabitacion.getText().trim();
    double precio;
    try {
        String precioTextoLimpio = precioTexto.replace(",", ".");
        precio = Double.parseDouble(precioTextoLimpio);
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Precio inválido. Use solo números (Ej: 50.5).",
                "Error en precio",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    String estado = cmbEstadoHabitacion.getSelectedItem().toString();

    Habitacion nueva = new Habitacion(numero, capacidad, precio, tipo, estado);
    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Habitación creada en memoria (falta guardarla en SistemaHotel).",
            "Info",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
    );

    this.dispose();
    }//GEN-LAST:event_btnGuardarHabitacionActionPerformed

    private void btnLimpiarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarHabitacionActionPerformed
    txtNumeroHabitacion.setText("");
    txtCapacidadHabitacion.setText("");
    txtPrecioHabitacion.setText("");
    cmbTipoHabitacion.setSelectedIndex(0);
    cmbEstadoHabitacion.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpiarHabitacionActionPerformed

    private void btnCancelarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarHabitacionActionPerformed
    this.dispose();
    }//GEN-LAST:event_btnCancelarHabitacionActionPerformed

    private void txtCapacidadHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidadHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidadHabitacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistroDeHabitacion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarHabitacion;
    private javax.swing.JButton btnGuardarHabitacion;
    private javax.swing.JButton btnLimpiarHabitacion;
    private javax.swing.JComboBox<String> cmbEstadoHabitacion;
    private javax.swing.JComboBox<String> cmbTipoHabitacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCapacidadHabitacion;
    private javax.swing.JTextField txtNumeroHabitacion;
    private javax.swing.JTextField txtPrecioHabitacion;
    // End of variables declaration//GEN-END:variables
}
