/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modelo;

import clases.Huesped;

/**
 *
 * @author Chris
 */
public class RegistroDeHuespedes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroDeHuespedes.class.getName());
    private clases.SistemaHotel sistema;
    private Huesped huespedEditar;
    private Runnable onGuardado;
    /**
     * Creates new form RegistroDeHuespedes
     */

    public RegistroDeHuespedes() {
        this(new clases.SistemaHotel(), null, null);
    }

    public RegistroDeHuespedes(clases.SistemaHotel sistema, Huesped huespedEditar, Runnable onGuardado) {
        initComponents();
        setLocationRelativeTo(null);
        this.sistema = sistema;
        this.huespedEditar = huespedEditar;
        this.onGuardado = onGuardado;

        if (huespedEditar != null) {
            txtDniHuesped.setText(huespedEditar.getDni());
            txtNombresHuesped.setText(huespedEditar.getNombres());
            txtApellidosHuesped.setText(huespedEditar.getApellidos());
            txtTelefonoHuesped.setText(huespedEditar.getContacto());
            txtEmailHuesped.setText(huespedEditar.getEmail());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombresHuesped = new javax.swing.JTextField();
        txtApellidosHuesped = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDniHuesped = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTelefonoHuesped = new javax.swing.JTextField();
        txtEmailHuesped = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnCancelarHuesped = new javax.swing.JButton();
        btnLimpiarHuesped = new javax.swing.JButton();
        btnGuardarHuesped = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("REGISTRO DE HUESPEDES");

        jLabel4.setText("APELLIDOS:");

        jLabel2.setText("DNI:");

        jLabel3.setText("NOMBRES:");

        jLabel5.setText("EMAIL:");

        jLabel6.setText("TELEFONO:");

        btnCancelarHuesped.setText("CANCELAR");
        btnCancelarHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarHuespedActionPerformed(evt);
            }
        });

        btnLimpiarHuesped.setText("LIMPIAR");
        btnLimpiarHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarHuespedActionPerformed(evt);
            }
        });

        btnGuardarHuesped.setText("GUARDAR");
        btnGuardarHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarHuespedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(63, 63, 63))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(24, 24, 24)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombresHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDniHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidosHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnGuardarHuesped)
                            .addGap(59, 59, 59)
                            .addComponent(btnLimpiarHuesped)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelarHuesped))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5))
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTelefonoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEmailHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDniHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombresHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtApellidosHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTelefonoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEmailHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarHuesped)
                    .addComponent(btnLimpiarHuesped)
                    .addComponent(btnCancelarHuesped))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarHuespedActionPerformed
String dni = txtDniHuesped.getText().trim();
    String nombres = txtNombresHuesped.getText().trim();
    String apellidos = txtApellidosHuesped.getText().trim();
    String telefono = txtTelefonoHuesped.getText().trim();
    String email = txtEmailHuesped.getText().trim();

    if (dni.isEmpty() || nombres.isEmpty() || apellidos.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Complete los campos obligatorios (DNI, Nombres, Apellidos).",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    // Aquí podrías validar que el DNI y teléfono sean numéricos si quieres.

    if (huespedEditar == null) {
        if (sistema.buscarHuespedPorDni(dni) != null) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ya existe un huésped con ese DNI.",
                    "Aviso",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        Huesped nuevo = new Huesped(dni, nombres, apellidos, telefono, email, "ACTIVO");
        sistema.agregarHuesped(nuevo);
    } else {
        Huesped existente = sistema.buscarHuespedPorDni(dni);
        if (existente != null && existente != huespedEditar) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "El DNI ingresado pertenece a otro huésped.",
                    "Aviso",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        huespedEditar.setDni(dni);
        huespedEditar.setNombres(nombres);
        huespedEditar.setApellidos(apellidos);
        huespedEditar.setContacto(telefono);
        huespedEditar.setEmail(email);
    }

    if (onGuardado != null) {
        onGuardado.run();
    }

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Cambios guardados correctamente.",
            "Info",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
    );

    this.dispose();    }//GEN-LAST:event_btnGuardarHuespedActionPerformed

    private void btnLimpiarHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarHuespedActionPerformed
    txtDniHuesped.setText("");
    txtNombresHuesped.setText("");
    txtApellidosHuesped.setText("");
    txtTelefonoHuesped.setText("");
    txtEmailHuesped.setText("");
    }//GEN-LAST:event_btnLimpiarHuespedActionPerformed

    private void btnCancelarHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarHuespedActionPerformed
    this.dispose();
    }//GEN-LAST:event_btnCancelarHuespedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistroDeHuespedes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarHuesped;
    private javax.swing.JButton btnGuardarHuesped;
    private javax.swing.JButton btnLimpiarHuesped;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtApellidosHuesped;
    private javax.swing.JTextField txtDniHuesped;
    private javax.swing.JTextField txtEmailHuesped;
    private javax.swing.JTextField txtNombresHuesped;
    private javax.swing.JTextField txtTelefonoHuesped;
    // End of variables declaration//GEN-END:variables
}
